NO_EDGE = "NO_TRADE: NO_EDGE"
LIQUIDITY_FAIL = "NO_TRADE: LIQUIDITY_FAIL"
MISSING_MAPPING = "NO_TRADE: MISSING_MAPPING"
STALE_GAME_STATE = "NO_TRADE: STALE_GAME_STATE"
STALE_ORDERBOOK = "NO_TRADE: STALE_ORDERBOOK"

VETO_RISK_LIMIT_DAY = "VETO: RISK_LIMIT_DAY"
VETO_RISK_LIMIT_GAME = "VETO: RISK_LIMIT_GAME"
VETO_POSITION_LIMIT = "VETO: POSITION_LIMIT"

TRADE_NBA_SIGNAL = "TRADE: NBA_SIGNAL"
TRADE_SOCCER_VALUE = "TRADE: SOCCER_VALUE"
TRADE_SOCCER_EARLY_MISPRICING = "TRADE: SOCCER_EARLY_MISPRICING"
